language: php
php:
  - 5.6
  - 7.0
  - 7.1

sudo: required
dist: precise

install:
  - composer install

script:
- php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v